-- Create the database if it doesn't exist
CREATE DATABASE db;


-- Connect to the newly created or existing database
\c db;

-- Create the Users table
CREATE TABLE IF NOT EXISTS Users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    username VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL
);

-- Insert the default admin user
INSERT INTO Users (id, username, password) VALUES
-- password is set to "admin" by default
(0, 'admin', '$argon2id$v=19$m=65536,t=3,p=4$5WQDnJhM1XllcvB6go1T0w$DZrhYW9uJLtb0qqUXq0Gf9sgmn4pHmkLsrD2pwm45YM')
ON CONFLICT DO NOTHING;